In [2]:
# Numpy is a mutli dimensional array library which is used to store all sorts of data in arrays.
# Pretty important library for scientific computing.
import numpy as np

In [3]:
a = np.array([1, 2, 3], dtype = 'int32')
b = np.array([[9, 8, 7], [6, 5, 4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [4]:
# Get dimension
b.ndim

2

In [5]:
# Get shape
b.shape

(2, 3)

In [6]:
# Get type
a.dtype

dtype('int32')

In [7]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a, a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] (2, 7)


In [8]:
# Get a specific element [r, c]
a[1, 5]  # since python indexing starts from 0
a[1, -2]  # similar to lists

13

In [9]:
a[1, 5] = 20
a[0, :]  # Get a specific row
a[:, 4]  # Get a specific column

array([ 5, 12])

In [10]:
# [start index, stop index, step index]
a[:, 1: 6 : 2]


array([[ 2,  4,  6],
       [ 9, 11, 20]])

In [11]:
# Initializing different types of arrays
np.zeros((3, 3))  # All 0s matrix
np.ones((2, 2))  # All 1s matrix
np.full((2, 2), 7)  # Any other number

array([[7, 7],
       [7, 7]])

In [12]:
np.random.rand(4, 2)  # Random Integer values

array([[0.96086072, 0.77004509],
       [0.08673354, 0.60102567],
       [0.3949728 , 0.40102159],
       [0.68134298, 0.55050207]])

In [13]:
np.random.randint(1, 11, size = (3, 3))

array([[ 8,  1,  6],
       [10, 10,  2],
       [ 1,  3,  2]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
cool_matrix = np.ones((5, 5))
cool_matrix[1: 4, 1: 4] = np.zeros((3, 3))
cool_matrix[2, 2] = 9
cool_matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Be careful when copying arrays!!
a = np.array([1, 2, 3])
# b = a
# b[0] = 100
# print(a) # We modify the original array as well if we use this method:/
b = a.copy()
b[0] = 100
print(a, b)

[1 2 3] [100   2   3]


In [17]:
a = np.array([1, 2, 3, 4])
print(a)
print(a + 2)
print(a - 2)
print(a * 2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]


In [18]:
b = np.array([1, 0, 1, 0])
print(a + b)

[2 2 4 4]


In [19]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [20]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

#### Statistics

In [21]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(stats))
print(np.max(stats, axis=1))  # returns the maximum value of each row>

1
[3 6]


In [22]:
np.sum(stats)

21

#### Reorganizing Arrays

In [23]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
after = before.reshape((4, 2))
print(before.shape, after.shape)
print(after)

(2, 4) (4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:

v1 = np.array([1, 2, 4])
v2 = np.array([9, 5, 2])

np.hstack([v1, v2])  #Horizontally stacking vectors
np.vstack([v1, v2])  # Vertically stacking vectors



array([[1, 2, 4],
       [9, 5, 2]])

In [25]:
[]

[]